### ISSUE TITLE
mesh release date ?

### ISSUE THREAD

**Issue by ihubgit** [TechnitiumSoftware/BitChatClient#10]
Hi, it's not really a technical issue, but was just wondering when the mesh client will be out, as it was announced for the end of last month... It's being awaited for with anticipation !

**Comment by ShreyasZare** [comment]
Hi. Thanks for the post. There is no fixed release date for Mesh. It would be out as soon as I manage to get some time in finalizing it. It should be available in a month's time mostly.

**Comment by ihubgit** [comment]
ok keeping my fingers crossed...

**Comment by ihubgit** [comment]
Just a small add-on if you don't mind. Would it be possible to already implement the cross-platform feature at the same time ?

**Comment by ShreyasZare** [comment]
> Just a small add-on if you don't mind. Would it be possible to already implement the cross-platform feature at the same time ?

Cross platform support is not yet in place since ECDiffieHellman that is being used is not available in .NET standard 2.0 and .NET Standard 2.1 is not yet supported with .NET Framework. Its a mess now which I hope Microsoft fixes very soon.

Another issue is with GUI as its only available for Windows. I am planning to have a web interface for Mesh in later major release so that it would work with any web browser just like how the other project, DNS Server, has web console to access the locally running app.

An update: Mesh should be available by next weekend. Final tests are on going as of now.

**Comment by ihubgit** [comment]
great ! looking forward to it.

**Comment by mva1985** [comment]
Looking forward to it as well...  willing to test message with anyone if you want

**Comment by ShreyasZare** [comment]
Mesh is now released! Get it from [mesh.im](http://mesh.im)

**Comment by mva1985** [comment]
It looks good so far...  My user id if anyone wants to test Mesh out.... d9acf0d1cd34855c2664dbcab1d971804bd855a3
