### ISSUE TITLE
skip registration.

### ISSUE THREAD

**Issue by erherhh4herh** [TechnitiumSoftware/BitChatClient#4]
this application seems interesting. however, i fail to understand why registration is required to use it... it would be great if this had the option to not register and just enter in an alias, and add people to chat rooms via randomized account tokens... thank you!

**Comment by ShreyasZare** [comment]
Thanks for the feedback. I have spent a good amount of time on this and felt that having a digital certificate for identity verification to be a better choice in long term. Since, this chat app works totally peer-to-peer (we don't even host any relay servers), similar to Bit torrent, being able to reliably identify a random user on a unknown IP address is very important than you might think.

If there was no registration (digital certificate) then each user was on his own to identify each peer on the opposite side which is really a dangerous situation. Any simple social engineering trick would have been sufficient enough to fool the user in believing who the peer is and there would be a real threat of information being leaked.

If you are still interested in such a peer-to-peer chat system, then there is already an app called Tox which uses hash of your public key as an identifier to initiate chat. While this works well, its open to social engineering hacks which may catch even a paranoid user off guard.
