### ISSUE TITLE
Spec?

### ISSUE THREAD

**Issue by SkyzohKey** [TechnitiumSoftware/BitChatClient#8]
Hello Guy,

I'm a client developer for the Tox project which is pretty similar to your project.

I plan to move to another lib and have some questions whose need answers.

How does bitchat compares to Tox? what are the main features? Any roadmap on future work? Is there a library that implements the protocol? Has the protocol a documented spec? Does it works reliably offline? How is name resolution being proceeded? Are audio/video calls available? Do you have API documentation? How big is the community?

I'm asking because Tox development is slow these days and I'd like to move to something else.

Note that the current client I'm building does runs on the web (does/can Bitchat supports webrtc/websockets), on Linux/OSX/Windows and mobile platforms such as Android, iOS, Windows Phone and XBox.

Would be nice if you can write a big explicative answer so that I can decide whether or not I'm willing to put effort refactoring my app so that it works with Bitchat.

Also, I'd be glad to help implementing stuff if that's needed.

Thanks in advance.

Kind regards,
SkyzohKey

**Comment by ShreyasZare** [comment]
Hi SkyzohKey,

Thanks for your interest in Bit Chat. 

I am aware of Tox, have used it for a while. Its quite good with client apps on most platforms. Bit Chat was an idea I had about having p2p IM and it took a while to make due to time/resource issues. Both Tox and Bit Chat are p2p but the architecture is quite different. Bit Chat protocol implementation is still not mature or stable and there are a few things that will be added or removed to make it more stable and secure.

Feature wise, Bit Chat provides private chat, group chat and file transfer. Features like audio/video calls etc are planned but still not implemented. The app can work without Internet (i.e. on LAN/WiFi networks) and only needs Internet initially for registering profile digital certificate. For peer resolution, it works similar to Bittorrent and uses both torrent trackers and DHT together.

The source code is in c# .NET and I am working on to make it with .NET Standard 2.0 for cross platform capability. Mobile app will be based on Xamarin.

There is no documentation or specification available apart from a whitepaper. This is due to the fact that I am working alone on this project and there is just not enough time for additional things.

Regarding web based client support (using webRTC/websockets), I am not inclined towards this since it breaks the p2p aspect of the entire system. Web app will require hosting on a central server and can potentially be manipulated by the maintainer/administrator. Only desktop and mobile apps are expected to be made. Mobile app development is paused till the core protocol implementation gets stable due to time constraints.

Next release is focused on improving the protocol and adding Tor hidden service option to anonymity. There is also a plan to change the product brand name.

If you have any further queries, please email them to support@bitchat.im.

Regards,
Shreyas Zare
